apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ruby-application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: ruby-app-project
  source:
    repoURL: https://github.com/dnoronh/ruby-app-gitops-repo.git
    path: deployment/ruby-app
    targetRevision: initial
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
