apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argocd
  name: ruby-application-appset
spec: 
  generators:
  - list:
      elements:
      - cluster: k3d-my-app-cluster
        url: https://kubernetes.default.svc
        namespace: app

      #We can add multiple cluster combinations here. 

      # - cluster: k3d-my-app-cluster-2
      #   url: https://1.2.3.4
      #   namespace: uat
      # - cluster: k3d-my-app-cluster-3
      #   url: https://9.8.7.6
      #   namespace: prod

  template:
    metadata:
      name: '{{cluster}}-ruby-application'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/dnoronh/ruby-app-gitops-repo.git
        path: deployment/ruby-app
        targetRevision: main
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
