name: docker-build-deploy

# For demo purpose, manual run is used. Ideally the workflow should run on commit push
on:
  workflow_dispatch:
    inputs:
      app_version:
        required: true
        default: '2.0'
        type: choice
        description: Version of Ruby app to build and deploy
        options: 
        - "1.0"
        - "2.0"
  # push:
  #   branches: [ "initial" ]

jobs:
  #This build job is only for demo purpose. Actual build happens in local, as we are using k3d local registry.
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker build -t ghcr.io/ruby-app:${git_hash} ./docker-build/${{ inputs.app_version }} 
          #docker push ghcr.io/ruby-app:${git_hash}    # Image to be pushsed to destination repository

  update-tag:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
    - uses: actions/checkout@v3
    - name: Update Helm image tag
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN_GITOPS }}
      run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          chmod +x ./docker-build/update-tag.sh
          git config --global user.email "demo_bot@github.com"
          git config --global user.name "demo_bot"

          #Override for local setup
          git_hash=${{ inputs.app_version }} 
          ./docker-build/update-tag.sh $git_hash
          echo "Updated image version to $git_hash"
