name: docker-build-deploy

on:
  workflow_dispatch:
  push:
    branches: [ "initial" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker build -t ghcr.io/ruby-app:${git_hash} ./docker-build
          #docker push ghcr.io/ruby-app:${git_hash}    # Image to be pushsed to destination repository

  update-tag:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
    - uses: actions/checkout@v3
    - name: Update Helm image tag
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN_GITOPS }}
      run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          chmod +x ./docker-build/update-tag.sh
          git config --global user.email "delnor10@github.com"
          git config --global user.name "dnoronh"

          ./docker-build/update-tag.sh $git_hash
          echo "Updated image version to $git_hash"
